name: CI workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
      run-on: ubuntu-latest

      steps:
        - name: Checkout code
        uses: actions/checkout@v2
        
        - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

        - name: Install Dependencies
          run: pip install -r requirents.txt

        - name: Run Tests
          run: pytest